
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 20 21:12:21 CST 2020
//----------------------------------------------------

package TicTacToe;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TSTRING = 52;
  public static final int CHAR = 36;
  public static final int MULTDIV = 38;
  public static final int ELSIF = 26;
  public static final int CASE = 35;
  public static final int INTEGER = 45;
  public static final int INT = 2;
  public static final int CHARVAL = 42;
  public static final int FOR = 21;
  public static final int WRITE = 9;
  public static final int DELIM = 12;
  public static final int SUMRES = 37;
  public static final int AND = 20;
  public static final int IGUAL = 18;
  public static final int CWHILE = 24;
  public static final int ARRAYDDVALI = 50;
  public static final int OR = 19;
  public static final int BOOL = 5;
  public static final int COMMA = 15;
  public static final int CLOSEFUNC = 14;
  public static final int OPENFUNC = 13;
  public static final int ARRAYDDVALC = 48;
  public static final int MAIN = 8;
  public static final int IF = 25;
  public static final int WRITELN = 10;
  public static final int ID = 46;
  public static final int ARRAYD = 43;
  public static final int ARRAYDD = 44;
  public static final int EOF = 0;
  public static final int PARIZQ = 16;
  public static final int RETURN = 33;
  public static final int ARRAYDVALI = 49;
  public static final int error = 1;
  public static final int BOOLVAL = 41;
  public static final int NULL = 40;
  public static final int ARRAYDVALC = 47;
  public static final int BOOLEX = 39;
  public static final int BREAK = 34;
  public static final int VOID = 6;
  public static final int SWITCH = 29;
  public static final int CIF = 28;
  public static final int ELSE = 27;
  public static final int FUNC = 7;
  public static final int READ = 11;
  public static final int CFOR = 22;
  public static final int WHILE = 23;
  public static final int DEFCASE = 32;
  public static final int CSWITCH = 30;
  public static final int STRING = 51;
  public static final int AS = 4;
  public static final int PARDER = 17;
  public static final int ENDCASE = 31;
  public static final int SET = 3;
}

